### ISSUE TITLE
Introspection compiles but returns invalid schema at runtime if you include a normal object in an input object

### ISSUE THREAD

**Issue by tpbowden** [absinthe-graphql/absinthe#507]
### Environment

* Elixir version (elixir -v): 1.6.1
* Absinthe version (mix deps | grep absinthe): 1.4.7 
* Client Framework and version (Relay, Apollo, etc): Any client

### Expected behavior

Invalid input objects raise a compile time, or at least a runtime error.

### Actual behavior

Schema with invalid input object does not raise any error, but the generated introspection schema is invalid. Different clients fail in different ways. `graphql-cli` fails like this:

`Introspection must provide input type for arguments.`

### Steps to reproduce

Create an input object like this:

```elixir

object :my_object do
  field :anything, :string
end

input_object :some_input do
  field :bad, :my_object
end

```

**Comment by benwilson512** [comment]
Fixed in master, will backport to 1.4 as well in a patch release

**Comment by tpbowden** [comment]
Awesome, thanks!

**Comment by inaniyants** [comment]
Looks like this fix was not backported to 1.4 and the problem is still reproduced. 
Probably, this is due to huge difference in this file between two branches:

https://github.com/absinthe-graphql/absinthe/compare/v1.4.13...master#diff-9ee072bcc09698a54f1da79567eaf411R1

@benwilson512 what about applying original fix to 1.4 branch ?

**Comment by tcoopman** [comment]
I'm also running into this. Any changes of backporting this?

**Comment by stueccles** [comment]
I ran into this as well on 1.4. Would be good to get this reopened and the fix backported.

**Comment by benwilson512** [comment]
1.5 is on RC, there will not be any further backports to 1.4 at this point.

**Comment by stueccles** [comment]
ok, awesome. Looking forward to getting on 1.5!
