### ISSUE TITLE
import_fields :non_existing_object does not raise on undefined objects

### ISSUE THREAD

**Issue by hubertlepicki** [absinthe-graphql/absinthe#634]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 19)

```
* Absinthe version (mix deps | grep absinthe):

```
* absinthe 1.4.13 (Hex package) (mix)
  locked at 1.4.13 (absinthe) 81eb2ff4
* absinthe_plug 1.4.5 (Hex package) (mix)
  locked at 1.4.5 (absinthe_plug) f63d52a7
* absinthe_phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (absinthe_phoenix) cea34e7e

```

* Client Framework and version (Relay, Apollo, etc):

```
none
```

### Expected behavior

When using `import_fields` to add fields to current object, if you specified non-existing object you would get and error.

### Actual behavior

`import_fields :non_existing_object` silently fails. No fields are obviously added to current object, but user is not being warned on the issue.

### Relevant Schema/Middleware Code

```
object :me do
  field(:id, non_null(:id))
  field(:email, non_null(:email))
  import_fields(:non_existing_object) # this silently fails, doing nothing but not crashing either
end

```

This is an issue because if you make typo while writing `import_fields` you will not get an error. The same issue will happen when you forget to first use relevant `import_types` macro before referencing object you want to import fields from.

**Comment by benwilson512** [comment]
Fixed in master, thanks!

**Comment by gabrielpra1** [comment]
Hey @benwilson512, the issue still seems to be happening in 1.4.16, only when importing outside the schema:

This compiles without a problem:

```elixir
  # schema.ex
  query do
    import_fields :test
  end

  # outside schema
  object :test do
    import_fields :non_existant
  end
```

This gives an error:

```elixir
  # schema
  query do
    import_fields :test
  end

  object :test do
    import_fields :non_existant
  end
```

**Comment by benwilson512** [comment]
We are not doing bug fixes for 1.4 sorry.
